In [36]:
from pathlib import Path

import pandas as pd
from datetime import datetime

from normalPayroll import NormalPayroll

In [37]:
normPay = NormalPayroll()

In [38]:
df1 = normPay.loadData()

In [39]:
df1['직책'] = df1['직책'].replace({'본부장(직무대행)':'본부장'})

In [40]:
df2 = normPay.mergeSudangDf(df1)
df2

,사원,사번,부서,직급,직책,출납,파견,적용년월,연봉,기본급,중식비,교통비,시간외수당,직책수당,통신비
0,강재영,201601001,동반위 운영국,본부장,운영국장,NaN,NaN,2016-02-01,130500000,10875000,130000,200000,0,1700000,100000
1,강재영,201601001,동반위 운영국,본부장,운영국장,NaN,NaN,2016-03-01,130500000,10875000,130000,200000,0,1700000,100000
2,강재영,201601001,동반위 운영국,본부장,운영국장,NaN,NaN,2016-04-01,130500000,10875000,130000,200000,0,1700000,100000
3,강재영,201601001,동반위 운영국,본부장,운영국장,NaN,NaN,2016-05-01,130500000,10875000,130000,200000,0,1700000,100000
4,강재영,201601001,동반위 운영국,본부장,운영국장,NaN,NaN,2016-06-01,130500000,10875000,130000,200000,0,1700000,100000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
588,심형택,201104002,상생결제운영부,1급,부장,NaN,NaN,2021-05-01,76518435,6376536,130000,200000,0,800000,50000
589,심형택,201104002,상생결제운영부,1급,부장,NaN,NaN,2021-06-01,79101027,6591752,130000,200000,0,800000,50000
590,심형택,201104002,상생결제운영부,1급,부장,NaN,NaN,2021-07-01,79101027,6591752,130000,200000,0,800000,50000
591,심형택,201104002,상생결제운영부,1급,부장,NaN,NaN,2021-08-01,79101027,6591752,130000,200000,0,800000,50000
592,심형택,201104002,상생결제운영부,1급,부장,NaN,NaN,2021-09-01,79101027,6591752,130000,200000,0,800000,50000

In [41]:
df3 = df2
df3['연도'] = df2['적용년월'].apply(lambda x: x.strftime('%Y'))
df3 = df3.groupby(['사원', '연도']).last()

In [42]:
df4 = df3.groupby(['사원', '사번']).last()
df4

,,부서,직급,직책,출납,파견,적용년월,연봉,기본급,중식비,교통비,시간외수당,직책수당,통신비
사원,사번,,,,,,,,,,,,,
강재영,201601001,동반위 운영국,본부장,운영국장,NaN,NaN,2019-11-01,141073682,11756140,130000,200000,0,1700000,100000
고근모,201804002,상생거래본부,본부장,본부장,NaN,NaN,2021-04-01,113862253,9488521,130000,200000,0,1000000,100000
국신욱,200803001,기획조정본부,1급,본부장,NaN,NaN,2021-09-01,84191048,7015920,130000,200000,0,1000000,100000
김관주,201309001,동반위 운영국,본부장,운영국장,NaN,NaN,2015-12-01,101371080,8447590,130000,200000,0,1700000,100000
김광곤,201804001,상생협력본부,본부장,본부장,NaN,NaN,2021-03-01,113862253,9488521,130000,200000,0,1000000,100000
김영환,201912003,동반위 운영국,본부장,운영국장,NaN,NaN,2021-09-01,147325360,12277113,130000,200000,0,1700000,100000
박노섭,201902007,농어촌상생기금운영본부,본부장,본부장,NaN,NaN,2021-02-01,113862253,9488521,130000,200000,0,1000000,100000
신기룡,201603001,상생거래본부,본부장,본부장,NaN,NaN,2018-03-01,108066639,9005553,130000,200000,0,1000000,100000
심형택,201104002,상생결제운영부,1급,부장,NaN,NaN,2021-09-01,79101027,6591752,130000,200000,0,800000,50000
윤형수,201110005,상생조정지원부,1급,부장,NaN,NaN,2021-09-01,87840307,7320025,130000,200000,0,800000,50000
이구익,202104002,상생거래본부,본부장,본부장,NaN,NaN,2021-09-01,114887013,9573917,130000,200000,0,1000000,100000
이상경,201104005,상생거래본부,본부장,본부장,NaN,NaN,2016-02-01,101371080,8447590,130000,200000,0,1000000,100000
이영숙,202109001,상생협력본부,본부장,본부장,NaN,NaN,2021-09-01,114887013,9573917,130000,200000,0,1000000,100000
이정화,201502001,상생협력본부,본부장,본부장,NaN,NaN,2018-02-01,108066639,9005553,130000,200000,0,1000000,100000
조태용,202103001,농어촌상생기금운영본부,본부장,본부장,NaN,NaN,2021-09-01,114887013,9573917,130000,200000,0,1000000,100000
한창훈,200411001,기술보호지원부,1급,부장,NaN,NaN,2021-09-01,92217661,7684805,130000,200000,0,800000,50000
홍성재,201703004,농어촌상생기금운영본부,본부장,본부장,NaN,NaN,2017-06-01,108066639,9005553,130000,200000,0,1000000,100000

In [47]:
con = df4.loc[:, '적용년월'] == datetime(2021,9,1)
filterIndex = df4.loc[con].index

In [51]:
filterIndex = [k[1] for k in filterIndex]
filterIndex

['200803001',
 '201912003',
 '201104002',
 '201110005',
 '202104002',
 '202109001',
 '202103001',
 '200411001']

In [54]:
con = df3.loc[:, '사번'].isin(filterIndex)
df3.loc[con]

                 사번           부서   직급    직책  출납  파견       적용년월         연봉  \
사원  연도
국신욱 2015  200803001        판로지원부   2급    부장 NaN NaN 2015-12-01   62526441
    2016  200803001     기술상용화지원부   2급    부장 NaN NaN 2016-12-01   64402234
    2017  200803001     생계형적합업종부   2급    부장 NaN NaN 2017-12-01   66656312
    2018  200803001       위원회운영부   2급    부장 NaN NaN 2018-12-01   69389221
    2019  200803001       기획조정본부   1급   본부장 NaN NaN 2019-12-01   76413796
    2020  200803001       기획조정본부   1급   본부장 NaN NaN 2020-12-01   81380693
    2021  200803001       기획조정본부   1급   본부장 NaN NaN 2021-09-01   84191048
김영환 2019  201912003      동반위 운영국  본부장  운영국장 NaN NaN 2019-12-01  141073680
    2020  201912003      동반위 운영국  본부장  운영국장 NaN NaN 2020-12-01  146011259
    2021  201912003      동반위 운영국  본부장  운영국장 NaN NaN 2021-09-01  147325360
심형택 2015  201104002      동반성장평가부   2급    팀장 NaN NaN 2015-12-01   62358036
    2016  201104002      혁신성장지원부   2급    부장 NaN NaN 2016-12-01   63265342
    2017  201104002      혁신성장지원부   2급    부장 NaN NaN 2017-12-01   65479629
    2018  201104002        기획경영부   2급    부장 NaN NaN 2018-12-01   67182099
    2019  201104002        경영지원부   2급    부장 NaN NaN 2019-12-01   71750482
    2020  201104002      협력성과확산부   1급    부장 NaN NaN 2020-12-01   76518435
    2021  201104002      상생결제운영부   1급    부장 NaN NaN 2021-09-01   79101027
윤형수 2015  201110005     생계형적합업종부   2급    부장 NaN NaN 2015-12-01   65864328
    2016  201110005     생계형적합업종부   2급    부장 NaN NaN 2016-12-01   67840254
    2017  201110005      적합업종지원실   2급    실장 NaN NaN 2017-12-01   70214663
    2018  201110005      혁신성장지원부   2급    부장 NaN NaN 2018-12-01   73093464
    2019  201110005      상생결제운영부   2급    부장 NaN NaN 2019-12-01   76601950
    2020  201110005      상생결제운영부   2급    부장 NaN NaN 2020-12-01   81772582
    2021  201110005      상생조정지원부   1급    부장 NaN NaN 2021-09-01   87840307
이구익 2021  202104002       상생거래본부  본부장   본부장 NaN NaN 2021-09-01  114887013
이영숙 2021  202109001       상생협력본부  본부장   본부장 NaN NaN 2021-09-01  114887013
조태용 2021  202103001  농어촌상생기금운영본부  본부장   본부장 NaN NaN 2021-09-01  114887013
한창훈 2015  200411001       마케팅협력부   2급    부장 NaN NaN 2015-12-01   66863820
    2016  200411001       위원회운영부   2급    부장 NaN NaN 2016-12-01   68822778
    2017  200411001      기술보호지원부   2급    부장 NaN NaN 2017-12-01   72263917
    2018  200411001      기술보호지원부   2급    부장 NaN NaN 2018-12-01   76310696
    2019  200411001      기술보호지원부   1급    부장 NaN NaN 2019-12-01   84499823
    2020  200411001      기술보호지원부   1급    부장 NaN NaN 2020-12-01   89569812
    2021  200411001      기술보호지원부   1급    부장 NaN NaN 2021-09-01   92217661

               기본급     중식비     교통비  시간외수당     직책수당     통신비
사원  연도
국신욱 2015   5210536  130000  200000      0   800000   50000
    2016   5366853  130000  200000      0   800000   50000
    2017   5554693  130000  200000      0   800000   50000
    2018   5782435  130000  200000      0   800000   50000
    2019   6367816  130000  200000      0  1000000  100000
    2020   6781724  130000  200000      0  1000000  100000
    2021   7015920  130000  200000      0  1000000  100000
김영환 2019  11756140  130000  200000      0  1700000  100000
    2020  12167604  130000  200000      0  1700000  100000
    2021  12277113  130000  200000      0  1700000  100000
심형택 2015   5196503  130000  200000      0   700000   50000
    2016   5272112  130000  200000      0   800000   50000
    2017   5456635  130000  200000      0   800000   50000
    2018   5598508  130000  200000      0   800000   50000
    2019   5979206  130000  200000      0   800000   50000
    2020   6376536  130000  200000      0   800000   50000
    2021   6591752  130000  200000      0   800000   50000
윤형수 2015   5488694  130000  200000      0   800000   50000
    2016   5653355  130000  200000      0   800000   50000
    2017   5851221  130000  200000      0   900000  100000
    2018   6091122  130000  200000      0   800000   50000
    2019   6383495  130000  200000      0   800000   50000
    2020   6814381  130000  200000      0   800000   50000
    2021   7320025  130000  200000      0   800000   50000
이구익 2021   9573917  130000  200000      0  1000000  100000
이영숙 2021   9573917  130000  200000      0  1000000  100000
조태용 2021   9573917  130000  200000      0  1000000  100000
한창훈 2015   5571985  130000  200000      0   800000   50000
    2016   5735231  130000  200000      0   800000   50000
    2017   6021993  130000  200000      0   800000   50000
    2018   6359224  130000  200000      0   800000   50000
    2019   7041651  130000  200000      0   800000   50000
    2020   7464151  130000  200000      0   800000   50000
    2021   7684805  130000  200000      0   800000   50000